package main

type TileMapData map[string]interface{}

// Generated by https://quicktype.io

type Tileset struct {
	Columns      int64     `json:"columns"`
	Image        string    `json:"image"`
	Imageheight  int64     `json:"imageheight"`
	Imagewidth   int64     `json:"imagewidth"`
	Margin       int64     `json:"margin"`
	Name         string    `json:"name"`
	Spacing      int64     `json:"spacing"`
	Tilecount    int64     `json:"tilecount"`
	Tiledversion string    `json:"tiledversion"`
	Tileheight   int64     `json:"tileheight"`
	Tiles        []Tile    `json:"tiles"`
	Tilewidth    int64     `json:"tilewidth"`
	Type         string    `json:"type"`
	Version      string    `json:"version"`
	Wangsets     []Wangset `json:"wangsets"`
}

type Tile struct {
	Animation []Animation `json:"animation"`
	ID        int64       `json:"id"`
}

type Animation struct {
	Duration int64 `json:"duration"`
	Tileid   int64 `json:"tileid"`
}

type Wangset struct {
	Colors    []Color    `json:"colors"`
	Name      string     `json:"name"`
	Tile      int64      `json:"tile"`
	Type      string     `json:"type"`
	Wangtiles []Wangtile `json:"wangtiles"`
}

type Color struct {
	Color       string `json:"color"`
	Name        string `json:"name"`
	Probability int64  `json:"probability"`
	Tile        int64  `json:"tile"`
}

type Wangtile struct {
	Tileid int64   `json:"tileid"`
	Wangid []int64 `json:"wangid"`
}
